egg_large:
    shop: Butchers
    unit: egg_large
    display_name: large eggs

bay_leaf:
    shop: Supermarket
    unit: bay_leaf
    display_name: bay leaves

banana:
    shop: Supermarket
    unit: banana
    display_name: bananas

apple:
    shop: Supermarket
    unit: apple
    display_name: apples

lemon:
    shop: Supermarket
    unit: lemon
    display_name: lemons

potato:
    shop: Supermarket
    unit: g
    display_name: potatoes

onion:
    shop: Supermarket
    unit: g
    display_name: onions

dill:
    shop: Supermarket
    unit: g
    display_name: dill

carrot:
    shop: Supermarket
    unit: g
    display_name: carrots

milk:
    shop: Supermarket
    unit: ml

water:
    shop: General
    unit: ml

thyme:
    shop: Supermarket
    unit: sprig
    display_name: thyme sprigs

nori:
    shop: Supermarket
    unit: nori_sheet
    display_name: nori sheets

garlic:
    shop: Supermarket
    unit: bulb
    display_name: garlic bulbs